### PR TITLE
chore(favicon): add favicon

### PR DESCRIPTION
**Pull request by johngruen**
This works. You may need to change the port to something else b/c in all likelihood the express favicon is cached in your browser.

### CODE REVIEW

**Comment by 6a68** [comment]
awesome, testing now

**Comment by 6a68** [comment]
@johngruen could we put the favicon in `public/images`?

**Comment by johngruen** [comment]
@6a68 could do...right now the `gulp build` task nukes the `public` directory and it's also in `.gitignore` We'd have to add a gulp task to move the `favicon.ico` file or rewrite current gulp tasks. Up to you.

**Comment by 6a68** [comment]
@johngruen oh, I see. It just seems weird to put an image top-level in a repo like that

**Comment by johngruen** [comment]
@6a68 actually i guess we could just put it in src/images and let the magic happen

**Comment by 6a68** [comment]
@johngruen it looks like `serve-favicon` caches the favicon for a year [by default](https://github.com/expressjs/serve-favicon#maxage). Do you think we should disable caching in dev?

**Comment by 6a68** [comment]
> @6a68 actually i guess we could just put it in src/images and let the magic happen
yeah, that sounds nice!

**Comment by 6a68** [comment]
We could disable caching in dev by pulling the maxFaviconAge from a config file. If you (understandably) don't want to get into that level of intensity, I'm fine to do it in a separate PR :-)

**Comment by 6a68** [comment]
Thanks @johngruen!

**Pull request merged**
